name: dta_pred
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - boost=1.68.0=py36h3e44d54_1
  - boost-cpp=1.68.0=h3a22d5f_0
  - bzip2=1.0.6=h470a237_2
  - cairo=1.14.12=h276e583_5
  - fontconfig=2.13.1=h65d0f4c_0
  - freetype=2.9.1=h6debe1e_4
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.56.2=h464dc38_1
  - icu=58.2=hfc679d8_0
  - jpeg=9c=h470a237_1
  - libffi=3.2.1=hfc679d8_5
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h470a237_3
  - libpng=1.6.36=ha92aebf_0
  - libtiff=4.0.10=he6b73bb_1
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - ncurses=6.1=hfc679d8_2
  - olefile=0.46=py_0
  - pandas=0.23.4=py36hf8a1672_0
  - pillow=5.3.0=py36hc736899_0
  - pip=18.1=py36_1000
  - pixman=0.34.0=h470a237_3
  - pthread-stubs=0.4=h470a237_1
  - pycairo=1.18.0=py36h4d1f301_0
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - readline=7.0=haf1bffa_1
  - setuptools=40.6.3=py36_0
  - six=1.12.0=py36_1000
  - sqlite=3.26.0=hb1c47c0_0
  - tk=8.6.9=ha92aebf_0
  - wheel=0.32.3=py36_0
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.3=h8c8a85c_0
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.4=h470a237_1
  - zlib=1.2.11=h470a237_3
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.0.2=py36_0
  - boto=2.49.0=py36_0
  - boto3=1.9.35=py36_0
  - botocore=1.12.35=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py36_0
  - cffi=1.11.5=py36he75722e_1
  - chardet=3.0.4=py36_1
  - cryptography=2.4.1=py36h1ba5d50_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - docutils=0.14=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=he6710b0_0
  - gensim=3.4.0=py36h14c3975_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - idna=2.7=py36_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.2.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.1=py36_0
  - jinja2=2.10=py36_0
  - jmespath=0.9.3=py36_0
  - joblib=0.13.0=py36_0
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libboost=1.65.1=habcd387_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - markupsafe=1.1.0=py36h7b6447c_0
  - matplotlib=3.0.2=py36h5429711_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2018.0.3=1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - notebook=5.7.2=py36_0
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - openssl=1.1.1a=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - prometheus_client=0.4.2=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - ptyprocess=0.6.0=py36_0
  - py-boost=1.65.1=py36hf484d3e_4
  - pycparser=2.19=py36_0
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.3.0=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.6.8=py36_0
  - python=3.6.7=h0371630_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.4.3=py36_0
  - requests=2.20.1=py36_0
  - s3transfer=0.1.13=py36_0
  - scikit-learn=0.20.1=py36h4989274_0
  - scipy=1.1.0=py36hfa4b5c9_1
  - send2trash=1.5.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - smart_open=1.7.1=py36_0
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tornado=5.1.1=py36h7b6447c_0
  - tqdm=4.28.1=py36h28b3542_0
  - traitlets=4.3.2=py36_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - widgetsnbextension=3.4.2=py36_0
  - zeromq=4.2.5=hf484d3e_1
  - rdkit=2018.09.1.0=py36h71b666b_1
  - pip:
    - absl-py==0.6.1
    - astor==0.7.1
    - biovec==0.2.4
    - bz2file==0.98
    - docopt==0.6.2
    - gast==0.2.0
    - grpcio==1.17.1
    - h5py==2.8.0
    - imbalanced-learn==0.4.3
    - imblearn==0.0
    - jsonpickle==0.9.6
    - keras==2.2.4
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - markdown==3.0.1
    - git+https://github.com/samoturk/mol2vec
    - munch==2.3.2
    - protobuf==3.6.1
    - py-cpuinfo==4.0.0
    - pyfasta==0.5.2
    - pymongo==3.7.2
    - pyyaml==3.13
    - sacred==0.7.4
    - seaborn==0.9.0
    - sklearn==0.0
    - tensorboard==1.12.1
    - tensorflow-gpu==1.12.0
    - termcolor==1.1.0
    - werkzeug==0.14.1
    - wrapt==1.10.11
prefix: /cta/users/hbilgin/.conda/envs/dta_pred
